const ONLINE_ROADMAP=[
 {id:'start',title:'1. Preparar el personaje',note:'Solo o con un compañero. El dinero del modo Historia no se transfiere al Online.',steps:[
 ['intro','Completar la introducción de GTA Online'],['home','Tener apartamento, garaje y vehículo asegurado'],['crew','Completar una actividad con otro miembro de tu misma Crew']]},
 {id:'activities',title:'2. Actividades y estancia',note:'Con un compañero: gana los deportes para avanzar también Número uno. Termina las partidas sin abandonarlas.',steps:[
 ['clothes','Comprar una prenda de ropa'],['hair','Cortarte el pelo'],['tattoo','Comprar un tatuaje de torso'],['dance','Pagar y terminar un baile privado'],['golf','Ganar una partida de golf'],['tennis','Ganar un set de tenis'],['darts','Ganar una partida de dardos'],['arms','Ganar una partida de pulseo'],['range-grid','Ganar en galería de tiro: cuadrícula'],['range-cover','Ganar en galería de tiro: objetivos con cobertura'],['range-random','Ganar en galería de tiro: objetivos aleatorios']]},
 {id:'races',title:'3. Carreras con un compañero',note:'Usa actividades originales de Rockstar. Para The Midnight Club, activa vehículos personalizados y selecciona tu vehículo propio modificado.',steps:[
 ['car','Preparar un vehículo propio personalizado'],['race-1','Ganar carrera terrestre con vehículo personalizado 1/5'],['race-2','Ganar carrera terrestre con vehículo personalizado 2/5'],['race-3','Ganar carrera terrestre con vehículo personalizado 3/5'],['race-4','Ganar carrera terrestre con vehículo personalizado 4/5'],['race-5','Ganar carrera terrestre con vehículo personalizado 5/5'],['gta-race','Ganar una carrera GTA'],['air','Ganar una carrera aérea'],['sea','Ganar una carrera marítima'],['parachute','Ganar una actividad de paracaidismo']]},
 {id:'group',title:'4. Sesión de cuatro jugadores',note:'Cuatro jugadores en total. En Rally el trofeo exige ganar como copiloto, no como conductor.',steps:[
 ['rally','Ganar una carrera Rally como copiloto'],['team-dm','Ganar un combate a muerte por equipos'],['dm','Ganar un combate a muerte individual (con un compañero)']]},
 {id:'combat',title:'5. Combate y servicios',note:'Lleva snacks, armadura y munición. Para la recompensa permanece activo al aire libre: actividades y propiedades pueden pausar el contador.',steps:[
 ['survival','Completar las 10 oleadas de una supervivencia'],['gang','Rango 18: completar un ataque a banda sin morir y matar tú a 10 enemigos'],['heli','Rango 20: llamar a Merryweather y pedir helicóptero de apoyo (no transporte)'],['bounty','Sobrevivir una recompensa durante un día del juego, unos 48 minutos reales'],['mugger','Dejar que un ladrón te robe, matarlo tú y recuperar el dinero; quien lo envía necesita rango 50']]},
 {id:'stores',title:'6. Atracar las 20 tiendas',note:'Marca cada tienda distinta según su ubicación en tu mapa. Apunta al dependiente, recoge el dinero y comprueba que el atraco queda registrado.',steps:Array.from({length:20},(_,i)=>['store-'+(i+1),'Tienda distinta '+(i+1)+'/20'])},
 {id:'finish',title:'7. Cerrar el platino',note:'Los checkpoints son una guía: marca el trofeo real en Trofeos cuando aparezca en PlayStation. Revisa Estadísticas → Premios para los 30 premios de categoría platino.',steps:[
 ['rank25','Alcanzar rango 25'],['rank50','Alcanzar rango 50'],['uno','Comprobar que ha saltado Número uno'],['stay','Comprobar que ha saltado Disfruta de la estancia'],['awards','Conseguir 30 premios de categoría platino (Condecorado)'],['rank100','Alcanzar rango 100; aprovechar actividades con bonificación de RP'],['firstperson','Acumular 15 horas en primera persona (Una nueva perspectiva)'],['platinum','Revisar los trofeos base pendientes y conseguir el platino']]},
 {id:'dlc',title:'Extra opcional: después del platino',note:'Estos grupos no son necesarios para el platino. El pack de Modo Director también es independiente y debe revisarse aparte.',optional:true,steps:[
 ['fleeca','Golpes: completar Fleeca'],['prison','Golpes: completar Fuga de prisión'],['humane','Golpes: completar Humane Labs'],['series','Golpes: completar Financiación inicial'],['pacific','Golpes: completar Pacific Standard'],['host','Financiar un golpe como líder y completar una preparación'],['cuts','Como líder, repartir 25 % a cada jugador en un final de cuatro'],['nodamage','Completar un final de golpe sin recibir daño'],['medals','Conseguir 25 medallas de platino en preparaciones y finales'],['vehicles','Gastar 8 millones en vehículos específicos de la actualización Golpes'],['doomsday-setup','Juicio Final: completar una preparación'],['doomsday1','Juicio Final: completar el acto I'],['doomsday2','Juicio Final: completar el acto II'],['doomsday3','Juicio Final: completar el acto III y comprobar A World Worth Saving'],['orbital','Eliminar un jugador con el cañón orbital'],['elite','Completar los desafíos de élite de los tres actos'],['master2','Completar Cerebro delictivo con equipo de 2'],['master3','Completar Cerebro delictivo con equipo de 3'],['master4','Completar Cerebro delictivo con equipo de 4']]}
];
