// Explicaciones originales en español; los enlaces permiten ampliar los requisitos.
const TROPHY_GUIDES={
0:['Consigue todos los demás trofeos del juego base, tanto Historia como Online.','Los packs de Golpes, Editor y Juicio Final no cuentan para el platino. La app es un registro manual: comprueba el desbloqueo en PlayStation.'],
1:['Completa la misión de Historia Franklin y Lamar.','Se obtiene al avanzar la campaña; no requiere medalla de oro.'],
2:['Completa la misión de Historia Fama o drama (Fame or Shame).','Avanza las misiones principales hasta reunir de nuevo a Michael y Trevor.'],
3:['Completa la misión principal Caída libre.','Se desbloquea al terminarla, sin requisitos extra de puntuación.'],
4:['Completa la misión principal Desenterrando el pasado (Bury the Hatchet).','No tienes que hacer ninguna actividad adicional.'],
5:['Completa una de las misiones finales de la campaña.','Elige la opción C si quieres conservar los tres protagonistas y evitar perder acceso a actividades. Guarda antes de elegir.'],
6:['Completa el golpe a la joyería Vangelico.','Cualquiera de los enfoques de la planificación sirve.'],
7:['Completa el golpe de Merryweather.','El enfoque elegido no cambia el requisito del trofeo.'],
8:['Completa la misión principal Bloqueo (Blitz Play).','Termina antes los preparativos que aparecen en el mapa.'],
9:['Completa el golpe de Paleto Bay.','Basta con terminar la misión, aunque no consigas oro.'],
10:['Completa el asalto al FIB (The Bureau Raid).','Cualquiera de los enfoques del golpe es válido.'],
11:['Completa El gran golpe, el atraco al Union Depository.','Termina los preparativos del enfoque que hayas elegido.'],
12:['Repite misiones desde Pausa → Partida → Repetir misión o Extraños y locos. Consigue oro en 70 misiones distintas.','Lee los objetivos de cada misión. Puedes mejorar requisitos en repeticiones diferentes; prioriza las misiones cortas.'],
13:['Consulta Pausa → Estadísticas → Lista del 100 %. Completa sus cinco bloques.','Requiere 69 misiones principales, 20 Extraños y locos computables, 42 aficiones, 14 eventos aleatorios y 16 actividades varias. No exige todas las actividades opcionales del mapa.'],
14:['Usa una avioneta o helicóptero para revelar las zonas oscuras del mapa, recorriéndolo en franjas.','Incluye también el mar cercano a la isla. Revisa los huecos tras recoger los residuos nucleares; no necesitas destapar cada píxel.'],
15:['Con Franklin, compra Downtown Cab Co. y espera una llamada de su encargado para una carrera privada.','Acepta el encargo y lleva al cliente al destino. Las carreras normales de taxi no sustituyen esta llamada.'],
16:['Con Trevor, compra McKenzie Field Hangar. Completa sus cinco misiones terrestres y cinco aéreas.','Usa el buggy y la avioneta del hangar. Aléjate y vuelve cuando necesites activar el siguiente encargo.'],
17:['Consigue al menos un oro en cada categoría: galería de tiro, escuela de vuelo, carrera callejera, carrera todoterreno, carrera marítima y triatlón.','No hace falta oro en todos los eventos de cada categoría.'],
18:['Inicia con Franklin la cadena de Omega y recoge las 50 piezas de nave.','Después vuelve con Omega y completa el encuentro final. Usa el mapa y el contador de Objetivos para registrar las piezas.'],
19:['Recoge los 50 fragmentos de carta del modo Historia.','Con Franklin, completa después la misión de Dreyfuss que se desbloquea. Para el trofeo, acaba con él.'],
20:['Compra el muelle Sonar Collections Dock después de que esté disponible en la campaña.','Usa el sumergible del muelle y la aplicación de rastreo para recoger los 30 barriles bajo el agua. Regístralos en Objetivos.'],
21:['Con Trevor, completa las cinco masacres señaladas con una calavera.','Se desbloquean en cadena. Si no ves la siguiente, comprueba que estás jugando como Trevor y que has terminado la anterior.'],
22:['Completa con éxito los 50 saltos acrobáticos del modo Historia.','Franklin ayuda con su habilidad de conducción. Una caída o aterrizar fuera de la zona válida no cuenta: espera el mensaje de salto completado.'],
23:['Con Michael, entra en epsilonprogram.com desde el teléfono y realiza la evaluación. Sigue después los encargos Epsilon.','Incluye donaciones, entrega de vehículos, búsqueda de objetos, llevar la túnica 10 días del juego y caminar unos 8 km en el desierto con ella. Termina la misión final; los tratados posteriores no son necesarios para este trofeo.'],
24:['Con uno de los protagonistas, llama a los otros dos para quedar juntos y recoge a ambos en un vehículo de cuatro plazas.','Fuera de una misión, consigue al menos tres estrellas y mantenlas durante tres minutos sin morir ni perder a los compañeros. Guarda antes de intentarlo.'],
25:['En modo Historia, ve mar adentro hasta que aparezca un tiburón como punto rojo en el radar.','Sal al agua y deja que te mate. No basta con verlo ni con matarlo. Guarda antes para recuperar tu situación.'],
26:['Con Trevor, recoge a un pasajero de un evento aleatorio que permita llevarlo al Culto Altruista.','En lugar del destino solicitado, llévalo al campamento marcado en el monte Chiliad. Guarda antes: las oportunidades válidas son limitadas.'],
27:['Acumula 200 millones de dólares gastados entre Michael, Franklin y Trevor.','Una forma de aumentar el gasto registrado es comprar y vender acciones repetidamente con capital suficiente. Es gasto acumulado, no dinero que debas conservar al mismo tiempo.'],
28:['Compra acciones desde el teléfono y véndelas cuando su precio haya subido respecto a tu compra.','Comprueba el beneficio en tu cartera; necesitas una venta con ganancias. No es necesario dominar toda la bolsa.'],
29:['En Ammu-Nation, elige un arma que tenga accesorios disponibles y compra todas sus mejoras aplicables.','Incluye cargador, accesorios y un acabado comprado. Una pistola con accesorios desbloqueados es una opción sencilla.'],
30:['Con Trevor, acepta los encargos de Maude y localiza uno de sus objetivos.','Haz que se rinda sin matarlo y llévalo a Maude. Guarda antes del encuentro: si matas a todos los objetivos, pierdes la oportunidad en esa partida.'],
31:['Lleva un coche con suficientes opciones de modificación a Los Santos Customs. Compra una mejora de cada categoría disponible.','Revisa rendimiento, carrocería, pintura, luces, matrícula, ruedas y accesorios de neumáticos. Sal del taller para que se compruebe el trofeo.'],
32:['En modo Historia, completa los 50 vuelos bajo puentes y los 15 vuelos a cuchillo.','Los puentes se hacen sin tocar su estructura. Para vuelo a cuchillo necesitas una avioneta pasando de lado por el hueco válido. Guarda y usa los contadores de Objetivos.'],
33:['Cambia la cámara a primera persona y acumula 15 horas de juego con esa vista.','Puedes avanzar mientras haces otras actividades. Comprueba el tiempo en Estadísticas y vuelve a primera persona si una actividad cambia la cámara.'],
34:['Completa la introducción que te ofrece GTA Online para tu personaje.','No la omitas al crear un personaje nuevo. La secuencia varía según versión y personaje migrado; revisa si el trofeo ya figura en PlayStation antes de repetirla.'],
35:['Gana RP con misiones, carreras y otras actividades hasta rango 25.','Los checkpoints del roadmap permiten conseguir otros trofeos mientras subes.'],
36:['Sigue ganando RP hasta rango 50 en GTA Online.','Prioriza actividades con bonificación de RP y termina los objetivos variados antes de repetir una sola misión.'],
37:['Alcanza rango 100 con el personaje de GTA Online.','Alterna misiones y actividades con bonificación de RP. El dinero no sube el rango por sí solo: necesitas experiencia RP.'],
38:['Gana carreras terrestre, aérea, marítima, GTA y Rally; paracaidismo; combates a muerte individual y por equipos; golf, tenis, dardos y pulseo; y un desafío competitivo en la galería de tiro.','Además completa un ataque a banda y las 10 oleadas de supervivencia. Usa actividades originales de Rockstar y acaba cada partida.','Necesitarás un compañero para muchas victorias y cuatro jugadores en total para Rally. Si no salta, revisa los checkpoints y prueba los tres tipos de desafío de tiro.'],
39:['Ten un vehículo propio personalizado de la clase admitida en la carrera. Activa Vehículos personalizados y selecciona ese vehículo.','Gana cinco carreras contra al menos otro jugador. Con un compañero podéis alternar victorias en un circuito corto.'],
40:['Entra en una supervivencia y completa sus 10 oleadas en una misma partida.','Un grupo con buena cobertura facilita el intento. Lleva armadura y snacks; las supervivencias clásicas se desbloquean durante la progresión inicial.'],
41:['Organiza una carrera terrestre compatible y cambia el tipo a Rally. Necesitas cuatro jugadores: dos equipos de conductor y copiloto.','Selecciona el papel de copiloto y consigue que gane tu equipo. Ganar como conductor no da este trofeo.'],
42:['Consigue que te pongan una recompensa: un compañero puede llamar a Lester cuando tenga el servicio disponible.','Sobrevive aproximadamente 48 minutos reales en modo libre. Una sesión por invitación reduce el riesgo; permanece activo fuera de propiedades y actividades para no pausar el tiempo.'],
43:['Desde rango 18, busca un ataque a banda activo, marcado con un círculo rojo.','Mata personalmente al menos a 10 enemigos y completa el ataque sin morir. Usa cobertura y evita que otros jugadores se lleven las bajas que necesitas.'],
44:['Abre Pausa → Estadísticas → Premios y consigue 30 premios en categoría platino.','Prioriza los que tengas cerca de completar y aprovecha carreras y actividades del roadmap. No son trofeos de PlayStation ni medallas de mejor jugador en los golpes.'],
45:['Atraca las 20 tiendas distintas del Online, no las del modo Historia.','Apunta al dependiente, recoge el dinero y comprueba la marca del atraco en el mapa. Lleva control por ubicaciones para no repetir siempre las mismas.'],
46:['Completa estas diez actividades con el mismo personaje: comprar ropa, corte de pelo, tatuaje, golf, tenis, dardos, desafío de tiro, pulseo, atraco a tienda y baile privado.','No necesitas ganarlas para este trofeo, pero ganar los deportes avanza Número uno. No abandones a mitad de partida. Si no salta, prueba otro tatuaje de torso comprado en un local normal.'],
47:['Únete a una Crew y actívala. Invita a otro miembro de esa misma Crew a una actividad.','Termina una misión o carrera con él. Estar en una Crew sin jugar con otro miembro no basta.'],
48:['Pide a un compañero con rango 50 y el servicio desbloqueado que llame a Lamar y te envíe un ladrón.','Lleva dinero en efectivo. Deja que te robe y después mata tú al ladrón y recoge el dinero. El requisito de rango corresponde a quien lo envía.'],
49:['Desde rango 20 y con el servicio disponible, abre el teléfono y llama a Merryweather.','Pide Helicóptero de apoyo y paga el servicio. No elijas Recogida en helicóptero, que es transporte.'],
50:['Compra un apartamento con garaje desde Dynasty 8 y guarda un vehículo asegurado.','Comprueba el seguro y el localizador en Los Santos Customs si el vehículo no los tiene. El garaje del apartamento cubre la parte de garaje.'],
51:['Completa una misión de preparación de los golpes originales, por ejemplo una preparación de Fleeca.','Puedes participar como miembro del equipo; no necesitas ser líder.'],
52:['Completa los finales de Asalto a Humane Labs y Financiación inicial (Series A Funding).','Puedes ser líder o miembro; ambos golpes necesitan cuatro jugadores.'],
53:['Completa los finales de Fleeca y Pacific Standard.','Fleeca se hace con dos jugadores; Pacific Standard, con cuatro. Puedes participar como miembro del equipo.'],
54:['Completa el final de Fuga de prisión con un equipo de cuatro jugadores.','Puedes ser líder o miembro. Acabada la misión, espera a la pantalla de resultados.'],
55:['Alcanza rango 12 y consigue un apartamento de gama alta con sala de planificación para alojar golpes originales.','Recibe la introducción de Lester, inicia un golpe desde la sala y paga su coste de preparación. No basta con unirte al golpe de otro jugador.'],
56:['Como líder de un golpe original de cuatro jugadores, fija el reparto del final en 25 % para cada participante.','Confirma los cuatro porcentajes en la pantalla de planificación y completa el final. Fleeca no sirve porque solo admite dos jugadores.'],
57:['Acumula 8 millones de GTA$ en compras de vehículos de la actualización Golpes.','No cuenta cualquier vehículo. Confirma que pertenece a esa actualización antes de comprar; por ejemplo, el Insurgent y la Valkyrie forman parte de ella. No necesitas gastar todo de una vez.'],
58:['Completa un final de golpe original sin recibir daño en ese intento.','Fleeca con un compañero coordinado suele ser una opción sencilla. Evita disparos y accidentes: curarte después no elimina el daño ya recibido.'],
59:['Consigue 25 medallas de platino en resultados de preparaciones y finales de los golpes originales.','Puedes repetir misiones. Acuerda los papeles con el equipo para maximizar tu contribución y revisa la medalla de resultados. Estas medallas son distintas de los premios de Condecorado.'],
60:['En la versión actualizada, entra en Modo Director como actor, sal y repite hasta cinco entradas completas.','Hazlo en la misma sesión de juego. Donde exista el Editor Rockstar, crear y exportar un vídeo es la alternativa original.'],
61:['Entra y sal de Modo Director diez veces como un actor desbloqueado, en la misma sesión.','Donde exista el Editor Rockstar, también puedes crear y exportar diez vídeos. En PS4 el Editor fue retirado: usa Modo Director.'],
62:['En Historia, encuentra y habla con los 12 personajes especiales que se desbloquean como actores.','Revisa la categoría Personajes especiales de Modo Director. Cuando estén todos desbloqueados, entra con uno de ellos.'],
63:['Desde Historia, abre el menú de interacción y selecciona Modo Director.','Elige un actor ya disponible y entra al escenario; abrir solamente el menú de selección no basta.'],
64:['En Historia, consume un peyote terrestre o aéreo para desbloquear un actor animal.','Termina la alucinación, abre Modo Director y entra con ese animal.'],
65:['Avanza la Historia y completa las misiones necesarias para desbloquear todos los actores de Personajes de Historia.','Comprueba los que siguen bloqueados en el menú de actores; después entra con uno de esa categoría.'],
66:['Completa la cadena Epsilon de Michael para desbloquear a Cris Formage.','Abre Modo Director, búscalo en Personajes de Historia y entra como él.'],
67:['En Modo Director, abre el menú de interacción y usa Localización para visitar cada destino de su lista.','Teletranspórtate a todos, recorriendo la lista completa. No exige recorrer el mapa manualmente.'],
68:['Crea un personaje en GTA Online y guarda su progreso.','Vuelve a Historia, abre Modo Director y elige tu personaje en la categoría de personajes Online. Entra al escenario.'],
69:['Desbloquea los 21 actores animales computables recogiendo los peyotes terrestres y aéreos del modo Historia.','Los animales submarinos no cuentan para esta categoría. Revisa la lista de animales en Modo Director y entra como un animal después de desbloquearlos.'],
70:['Participa y termina una misión preparatoria del Golpe del Juicio Final.','El líder necesita una instalación para alojar este contenido; puedes unirte a otro líder. Las misiones admiten de dos a cuatro jugadores.'],
71:['Completa el final del acto I del Juicio Final: Filtraciones de datos.','Sirve como líder o miembro de un equipo de dos a cuatro jugadores.'],
72:['Completa el final del acto II del Juicio Final: El problema Bogdan.','No exige un desafío de élite ni Cerebro delictivo para este trofeo.'],
73:['Completa el final del acto III del Juicio Final: El escenario del Juicio Final.','Puedes hacerlo como líder o miembro del equipo.'],
74:['Completa los finales de los tres actos del Juicio Final con tu personaje.','Revisa cuál te falta si ya has jugado algunos como miembro de otros equipos. Los requisitos de élite son otro trofeo.'],
75:['Compra la mejora de cañón orbital para tu instalación y accede a su sala de control.','En una sesión compatible, paga un disparo y elimina a otro jugador. Coordínalo con un compañero; tener el cañón o disparar sin matar no basta.'],
76:['Supera la élite en los finales de los tres actos, sin muertes en ninguno.','Acto I: menos de 5 minutos y 30 segundos y 78 enemigos eliminados entre el equipo.','Acto II: menos de 15 minutos y menos del 5 % de daño al Avenger.','Acto III: menos de 30 minutos, 150 bajas de disparo a la cabeza entre el equipo y ningún fallo al hackear.','Los reinicios rápidos y saltar el trayecto invalidan la élite. Revisa los resultados de cada acto; no hace falta conseguir las tres élites en una sola sesión.'],
77:['Completa las tres variantes de Cerebro delictivo del Juicio Final: equipos de dos, tres y cuatro jugadores.','Para cada variante, conserva el mismo equipo y realiza las misiones requeridas en orden, en dificultad difícil cuando exista esa opción y sin muertes.','Comprueba el contador de cada miembro en Estadísticas → Premios → Juicio Final después de cada misión. Una muerte o pérdida de progreso obliga a rehacer la variante; no es el Cerebro delictivo de los golpes originales.']
};
const TROPHY_GUIDE_SOURCES={
17:'https://www.playstationtrophies.org/game/grand-theft-auto-5-ps4/trophy/99509-multi-disciplined.html',
23:'https://www.gamesradar.com/gta-5-kifflom-guide/',
38:'https://www.playstationtrophies.org/game/grand-theft-auto-5-ps4/trophy/99529-numero-uno.html',
46:'https://gta.fandom.com/wiki/Enjoy_Your_Stay',
60:'https://support.rockstargames.com/articles/52mq4lkIYroqlliAhdcSb4/gtav-title-update-1-68-notes-ps5-ps4-xbox-series-x-s-xbox-one-pc',
61:'https://support.rockstargames.com/articles/52mq4lkIYroqlliAhdcSb4/gtav-title-update-1-68-notes-ps5-ps4-xbox-series-x-s-xbox-one-pc',
62:'https://steamcommunity.com/sharedfiles/filedetails/?id=518445247',
69:'https://www.playstationtrophies.org/game/grand-theft-auto-5-ps4/trophy/120533-cryptozoologist.html',
76:'https://heist.host/job/doomsday-heist-elite-challenges',
77:'https://www.xboxachievements.com/forum/topic/458273-gta-v-dlc-the-doomsday-heist-guide-roadmap/'
};
